server:
  port: 8080

spring:
  application:
    name: itquizletspringbootapi

  profiles:
    active: no-auth

  datasource:
    driver-class-name: org.postgresql.Driver
    #url: ${DB_POSTGRES_URL}
    #username: ${DB_POSTGRES_USERNAME}
    #password: ${DB_POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5001/shop
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    open-in-view: false
