server:
  port: 8080

spring:
  application:
    name: itquizletspringbootapi

  profiles:
    active: no-auth

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-shrill-bush-a2bqnx02.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=r3atpYe2TLmD&sslmode=require
    username: neondb_owner
    password: r3atpYe2TLmD

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
